drop procedure getAllOrdersByCategoryName;
drop procedure getQtdOrdensProcessadas;
drop procedure getMesesSemOrders;
drop procedure get3MoreOrders;
drop procedure getMesesSemOrdersPChai;
drop procedure getMesesEAnosSemOrders;
drop procedure getListEmployeesWChai;
drop procedure getListEmployeesMoreOrders;
drop procedure getListEmployeesHasOrdersOwnCity;
drop procedure getListEmployeesHasOrdersNotOwnCity;
drop procedure getShippersHasOrderWSeafood;
drop procedure getCategoryHasEmployeesInUSA;
drop procedure getSupplierAndShipperNameFromCategory;
drop procedure updateBonusInEmployees;

CREATE PROCEDURE getAllOrdersByCategoryName (categoryName varchar(15)) PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getAllOrdersByCategoryName';
CREATE PROCEDURE getQtdOrdensProcessadas () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getQtdOrdensProcessadas';
CREATE PROCEDURE getMesesSemOrders () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getMesesSemOrders';
CREATE PROCEDURE get3MoreOrders () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.get3MoreOrders';
CREATE PROCEDURE getMesesSemOrdersPChai () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getMesesSemOrdersPChai';
CREATE PROCEDURE getMesesEAnosSemOrders () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getMesesEAnosSemOrders';
CREATE PROCEDURE getListEmployeesWChai () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getListEmployeesWChai';
CREATE PROCEDURE getListEmployeesMoreOrders () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getListEmployeesMoreOrders';
CREATE PROCEDURE getListEmployeesHasOrdersOwnCity () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getListEmployeesHasOrdersOwnCity';
CREATE PROCEDURE getListEmployeesHasOrdersNotOwnCity () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getListEmployeesHasOrdersNotOwnCity';
CREATE PROCEDURE getShippersHasOrderWSeafood () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getShippersHasOrderWSeafood';
CREATE PROCEDURE getCategoryHasEmployeesInUSA () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getCategoryHasEmployeesInUSA';
CREATE PROCEDURE getSupplierAndShipperNameFromCategory () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 1 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.getSupplierAndShipperNameFromCategory';
CREATE PROCEDURE updateBonusInEmployees () PARAMETER STYLE JAVA LANGUAGE JAVA READS SQL DATA DYNAMIC RESULT SETS 0 EXTERNAL NAME 'com.github.clebermatheus.northwind.Derby.updateBonusInEmployees';

call getAllOrdersByCategoryName('Produce');
call getQtdOrdensProcessadas();
call getMesesSemOrders();
call get3MoreOrders();
call getMesesSemOrdersPChai();
call getMesesEAnosSemOrders();
call getListEmployeesWChai();
call getListEmployeesMoreOrders();
call getListEmployeesHasOrdersOwnCity();
call getListEmployeesHasOrdersNotOwnCity();
call getShippersHasOrderWSeafood();
call getCategoryHasEmployeesInUSA();
call getSupplierAndShipperNameFromCategory();
call updateBonusInEmployees();